name: Download Documents

on:
  workflow_dispatch:  # manually triggered

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install

    - name: Run script
      run: |
        python playwright-download.py